(function(g){function u(g){return null===g||"undefined"===typeof g}function F(g){return"[object Object]"===Object.prototype.toString.call(g)&&!u(g)}function G(g){return"[object Function]"===Object.prototype.toString.call(g)||"function"===typeof g}g._rnq=F(g._rnq)&&G(g._rnq.push)?g._rnq:function(){function L(){var a=p(/^[\-_.()*0-9a-z]{1,32}$/i);return function(c,b){return a(c,z(b,32))}}function v(a,c,b){for(var d=0;d<a.length;++d)c=b(c,a[d]);return c}function r(a,c,b){for(var d in a)a.hasOwnProperty(d)&&
(c=b(c,d,a[d]));return c}function M(a,c){return r(a,[],function(a,d,e){c.hasOwnProperty(e)||a.push(e);return a})}function $(a){this.g=a;return this}function A(a){return new $(function(c){return a.test(c)})}function B(a,c){return function(b,d){var e=a.g(d);e&&c&&c(b,d);return e}}function p(a){return B(A(a),aa)}function aa(a,c){k[a]=c}function w(a){return 2===a.length||3===a.length}function N(a){var c;if(c=5===a.length&&F(a[4])&&O(a[3]))a=a[2],c=C(a)&&/^(?:d(?:ebug)?|i(?:nfo)?|e(?:rror)?|f(?:atal)?)$/i.test(a);
return c}function z(a,c,b){if(a.length<=c)return a;a=a.substr(0,c-3);b&&(a=P(a.replace(/%.?$/,"")));return a+"..."}function P(a){var c;try{c=decodeURIComponent(a)}catch(b){c=!1}if(!1!==c)return a;c=a.replace(/%..$/,"");return a===c?a:P(c)}function ba(a){r(a,!0,function(a,b,d){return f.hasOwnProperty(b)&&f[b](b,d)||a})}function ca(a){v(a,void 0,function(a,b){"[object Array]"===Object.prototype.toString.call(b)?!w(b)&&!N(b)||!Q("subject",b[0])||!Q("verb",b[1])||50<=m.length||(w(b)?u(b[2])||(b[2]=z(b[2].toString(),
100).replace(/[\x00-\x1F\x7F]/g," ")):(b[3]=Math.floor(b[3]),b[2]=b[2].toLowerCase()[0],b[4]=da(b[4])),m.push(b)):F(b)?ba(b):G(b)&&x.push(b)})}function ea(a){if(!R){var c=new Image;c.onload=function(){h=k.e?2E3:15E3;m=m.slice(t);t=0;H()};c.onerror=function(){h*=1.5;t=0;S();H()};c.src=D+a}}function T(a,c,b){this.c=a;this.d=c;this.a=b;return this}function U(){for(var a=I((new Date).getTime()/100,5),c=fa(),b=2083-(g.location.protocol.length+D.length+c.length+a.length+2+4),d=[],e=[],f=-1;++f<m.length&&
0<b;){var q=m[f],l=q[0],h=q[1];if(w(q))var n=q[2],n=u(n)?"":","+s(n.toString().replace(/[|]/g,"(-pipe-)")),l=l+","+h+n,l=new T(l,l.length+(d.length?1:3),"");else n=q[3],l=l+","+h+","+q[2]+(0>=n?"":","+n),h=l.length+(e.length?1:3),n=V(q[4],e.length,b-h,0===d.length+e.length?10:0),l=new T(l,h+n.length,n);b-=l.d;if(0<=b)(w(q)?d:e).push(l.c),c+=l.a;else if(0==d.length+e.length)return m.pop(),U()}t=d.length+e.length;b=J(0,[k.f,k.p,k.v,k.b,k.i]);f=m.slice(0,t);b=v(f,v(f,b,ga),ha);return"Z="+a+I(b,4)+c+
(d.length?"&a="+d.join("|"):"")+(e.length?"&n="+e.join("|"):"")}function ga(a,c){if(w(c)){var b=c[2];return J(a,[c[0],c[1],u(b)?"":b])}return a}function ha(a,c){if(N(c)){var b=c[3];return J(a,[c[0],c[1],c[2],0<b?b.toString():""])}return a}function V(a,c,b,d){var e=W(c,a),f=e.length-b;if(0<d&&0<f){var g=r(a,0,X);if(0<g&&(e=r(a,{},function(a,c,b){if(C(b)){var d=s(b),e=X(0,0,b);0<e&&(b=decodeURIComponent(z(b,d.length-Math.ceil(f*e/g),!0)))}a[c]=b;return a}),e=W(c,e),e.length<=b))return e;delete a[Object.keys(a).pop()];
return V(a,c,b,d-1)}return e}function X(a,c,b){return C(b)?a+Math.max(0,s(b).length-50):a}function W(a,c){return r(c,"",function(b,c,e){var f=s(e.toString());return b+("&"+(("number"===typeof e?"%23":"$")+a+":"+c)+"="+f)})}function fa(){return r(k,"",function(a,c,b){c=s(c);b=s(b);return a+("&"+c+"="+b)})}function da(a){return r(a,{},function(a,b,d){(O(d)||C(d))&&(a[b.toString()]=d);return a})}function J(a,c){return v(c,a,ia)}function ia(a,c){for(var b=0;b<c.length;++b)a=(41*a+c.charCodeAt(b))%5E7;
return a}function I(a,c){if(0<c){var b=6*--c,b=a>>b&63;return String.fromCharCode(26>b?65+b:52>b?71+b:62>b?-4+b:63>b?45:95)+I(a,c)}return""}function ja(){y=void 0;var a=M(ka,k),c=M(Y,k);!a.length&&!u(D)&&c.length<Y.length&&(ea(U()),E=(new Date).getTime())}function H(){x.length&&(m.length?(h=0,clearTimeout(y),y=void 0):S());y||t||!m.length||18E5<h||(E=E||(new Date).getTime(),y=setTimeout(ja,Math.max(0,E+h-(new Date).getTime())))}function S(){if(x.length){var a=x;x=[];h=k.e?2E3:15E3;v(a,void 0,function(a,
b){b()})}}function O(a){return"number"===typeof a&&a<Math.pow(2,63)&&a>-Math.pow(2,63)}function C(a){return"string"===typeof a}function K(a){ca(a);h||(h=k.e?2E3:15E3);H()}var R=!1,s=encodeURIComponent,Z=/^[ -}]{1,25}$/,t,m=[],k={},E,D,y,h,x=[],f={};f.th=B(A(/^[\-a-z.:0-9]+$/i),function(a,c){D="//"+c+"/api/1/r?"});f.debug=function(a,c){return R=1==c};f.f=p(/^[a-z]{1,4}$/);f.p=p(Z);f.v=p(Z);f.b=p(/^[a-z0-9]{1,8}$/);f.i=p(/^[-_:a-z0-9]{1,97}$/i);f.s=L();f.as=L();f.e=p(/^[\-_0-9a-z]{8}$/i);f.uc=f.u=B(A(/^[!-~]*$/),
function(a,c){var b=c.replace(/^https?:\/\//,""),b=z(s(b),600,!0);k[a]=decodeURIComponent(b)});f.uh=p(/^[0-9a-f]{8}$/i);var ka=["f","p","v","b","i"],Y=["s","e"],Q=B(A(/^[\-0-9a-z]{1,25}$/i),null);K(function(a){var c=g.performance;if(c&&c.timing&&c.navigation&&G(g.addEventListener)){var b=c.timing,d=Math.max(1,b.responseEnd-b.requestStart),e={redirectCount:c.navigation.redirectCount,navType:c.navigation.type},c=function(){g.setTimeout(function(){var a=Math.max(1,b.loadEventEnd-b.navigationStart);K([["script-page",
"load","i",a,e]])},1)};a.unshift(["script-page","response","i",d,e]);"complete"===g.document.readyState?c():g.addEventListener("load",c)}return a}(function(a){a.unshift(["script-page","view"]);return a}(function(a){return"[object Array]"===Object.prototype.toString.call(a)?a:[]}(g._rnq))));return{push:function(){K(Array.prototype.slice.call(arguments))}}}()})("undefined"===typeof window._rnq&&"undefined"!==typeof window.parent?window.parent:window);
